-- =========================================================
-- Gridster Plus - Linden dollar (in-world) payment path
-- Adds a second, non-Stripe way to buy Gridster Plus: paying
-- an in-world Second Life kiosk L$1,750 for 30 days. This does
-- not touch the existing Stripe monthly/annual/founding flows.
--
-- Idempotency: the Second Life money() event has no built-in
-- transaction id, so the kiosk script generates its own
-- payment_reference per payment attempt (see
-- second-life/gridster-plus-kiosk.lsl) and reuses that exact
-- reference across HTTP retries of the same payment. The
-- unique constraint below is what actually prevents a retried
-- Worker call from double-crediting.
--
-- Mutual exclusivity: Stripe and Linden Plus are two separate
-- expiry clocks on the same profiles.plus_current_period_end
-- column, so they must never both be "active" at once. An
-- active Stripe subscriber (is_plus=true, plus_price_tier in
-- monthly/annual/founding) who pays the kiosk is rejected with
-- reason=active_stripe_subscription and refunded in-world - see
-- credit_gridster_plus_linden_payment() below. A lapsed Stripe
-- member or an active Linden member is not blocked.
-- =========================================================

alter table public.profiles
drop constraint if exists profiles_plus_price_tier_check;

alter table public.profiles
add constraint profiles_plus_price_tier_check
  check (plus_price_tier is null or plus_price_tier in ('monthly', 'annual', 'founding', 'linden'));

comment on constraint profiles_plus_price_tier_check on public.profiles is
  'Valid Gridster Plus billing tiers. ''linden'' is the in-world Second Life kiosk payment path (no recurring Stripe billing).';

create table if not exists public.gridster_plus_linden_payments (
  id uuid primary key default gen_random_uuid(),
  sl_avatar_uuid text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount_linden integer not null,
  payment_reference text not null,
  object_uuid text not null,
  paid_at timestamptz not null default now(),
  plus_start timestamptz not null,
  plus_end timestamptz not null,
  bonus_amount integer not null,
  created_at timestamptz not null default now(),

  constraint gridster_plus_linden_payments_reference_unique unique (payment_reference),
  constraint gridster_plus_linden_payments_amount_positive check (amount_linden > 0),
  constraint gridster_plus_linden_payments_bonus_nonnegative check (bonus_amount >= 0)
);

create index if not exists gridster_plus_linden_payments_user_id_idx
  on public.gridster_plus_linden_payments (user_id);

create index if not exists gridster_plus_linden_payments_sl_avatar_uuid_idx
  on public.gridster_plus_linden_payments (sl_avatar_uuid);

comment on table public.gridster_plus_linden_payments is
  'One row per accepted in-world Linden dollar Gridster Plus kiosk payment. payment_reference is generated by the LSL kiosk script (no native SL transaction id exists) and is unique so a retried Worker call can never double-credit. Written only by the Cloudflare Worker service role via credit_gridster_plus_linden_payment().';
comment on column public.gridster_plus_linden_payments.payment_reference is
  'Synthetic idempotency key built by the kiosk script from payer key + object key + amount + timestamp + a fresh llGenerateKey() per payment attempt, cached and reused across retries of that same attempt.';
comment on column public.gridster_plus_linden_payments.object_uuid is
  'Key of the in-world kiosk object that received the payment.';
comment on column public.gridster_plus_linden_payments.plus_start is
  'Start of the 30-day period this payment purchased (later of now() or the prior plus_current_period_end at credit time).';
comment on column public.gridster_plus_linden_payments.plus_end is
  'plus_start + 30 days. Mirrors what was written to profiles.plus_current_period_end at credit time.';

alter table public.gridster_plus_linden_payments enable row level security;

drop policy if exists "Users can read their own linden plus payments" on public.gridster_plus_linden_payments;

create policy "Users can read their own linden plus payments"
on public.gridster_plus_linden_payments
for select
to authenticated
using (auth.uid() = user_id);

-- No insert/update/delete policy is defined for any client role, so only
-- the Supabase service role (used exclusively by the Cloudflare Worker)
-- can write to this table, mirroring gridster_plus_bonus_claims.

create or replace function public.credit_gridster_plus_linden_payment(
  target_sl_avatar_uuid text,
  target_amount_linden integer,
  target_payment_reference text,
  target_object_uuid text,
  target_bonus_amount integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_profile record;
  inserted_id uuid;
  computed_start timestamptz;
  computed_end timestamptz;
  new_balance integer;
begin
  -- `for update` locks this profile row for the rest of the transaction.
  -- Any concurrent writer to the same row - in practice, the Stripe webhook's
  -- `update public.profiles ... where user_id = ...` in stripe-webhook.js -
  -- blocks until this function commits or rolls back, and then re-reads the
  -- row it just wrote. That is what makes the Stripe-tier check below and
  -- the crediting further down a single atomic unit: there is no window
  -- between "check" and "write" for a webhook to land in.
  select user_id, is_plus, plus_price_tier, plus_current_period_end
  into target_profile
  from public.profiles
  where sl_avatar_uuid = target_sl_avatar_uuid
    and sl_verified = true
  limit 1
  for update;

  if target_profile.user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'unlinked_avatar');
  end if;

  -- Stripe and Linden Plus are mutually exclusive. An active Stripe-billed
  -- member (monthly/annual/founding) cannot also buy Linden Plus - the kiosk
  -- payment is rejected and refunded instead of stacking a second, competing
  -- expiry clock on top of the Stripe subscription. A lapsed/canceled Stripe
  -- member (is_plus = false) is not blocked here - they fall through to the
  -- normal activate/extend path below like any other non-member.
  if target_profile.is_plus and target_profile.plus_price_tier in ('monthly', 'annual', 'founding') then
    return jsonb_build_object(
      'ok', false,
      'reason', 'active_stripe_subscription',
      'current_tier', target_profile.plus_price_tier
    );
  end if;

  computed_start := greatest(now(), coalesce(target_profile.plus_current_period_end, now()));
  computed_end := computed_start + interval '30 days';

  insert into public.gridster_plus_linden_payments (
    sl_avatar_uuid,
    user_id,
    amount_linden,
    payment_reference,
    object_uuid,
    plus_start,
    plus_end,
    bonus_amount
  )
  values (
    target_sl_avatar_uuid,
    target_profile.user_id,
    target_amount_linden,
    target_payment_reference,
    target_object_uuid,
    computed_start,
    computed_end,
    target_bonus_amount
  )
  on conflict (payment_reference) do nothing
  returning id into inserted_id;

  if inserted_id is null then
    return jsonb_build_object('ok', true, 'duplicate', true, 'user_id', target_profile.user_id);
  end if;

  update public.profiles
  set is_plus = true,
      plus_status = 'active',
      plus_price_tier = 'linden',
      plus_current_period_end = computed_end
  where user_id = target_profile.user_id;

  insert into public.bling_balances (user_id, balance)
  values (target_profile.user_id, 1250)
  on conflict (user_id) do nothing;

  update public.bling_balances
  set balance = balance + target_bonus_amount
  where user_id = target_profile.user_id
  returning balance into new_balance;

  return jsonb_build_object(
    'ok', true,
    'duplicate', false,
    'user_id', target_profile.user_id,
    'plus_current_period_end', computed_end,
    'balance', new_balance
  );
end;
$$;

comment on function public.credit_gridster_plus_linden_payment is
  'Called by the Worker service role from POST /api/plus-linden-payment. Locks the target profile row (select ... for update) before checking or writing anything, so this check-then-write cannot race a concurrent Stripe webhook update. Rejects with reason=active_stripe_subscription if the profile already has an active monthly/annual/founding Stripe subscription (is_plus=true), so Stripe and Linden Plus stay mutually exclusive - no Linden payment row, no period change, no Bling Bits, no Stripe field changes on that path. Otherwise idempotent per payment_reference: extends Plus from the later of now() or the existing plus_current_period_end, adds 30 days, sets plus_price_tier = linden, and grants the Bling Bits bonus exactly once. Never touches stripe_customer_id/stripe_subscription_id.';
